# Generated by Django 4.2.11 on 2025-11-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='value',
            field=models.CharField(max_length=10),
        ),
    ]
