# Generated by Django 5.2.8 on 2025-12-05 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_tile_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tile',
            options={'ordering': ('row', 'col')},
        ),
        migrations.AddField(
            model_name='tile',
            name='unicode_value',
            field=models.CharField(default='☐', max_length=10),
        ),
    ]
