# Generated by Django 5.2.8 on 2025-12-05 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_tile_options_tile_unicode_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='unicode_value',
            field=models.CharField(max_length=10),
        ),
    ]
