# Generated by Django 5.2.8 on 2025-12-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_tile_unicode_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='unicode_value',
            field=models.BooleanField(default=True),
        ),
    ]
